### ISSUE TITLE
Tests on Travis CI are failing

### ISSUE THREAD

**Issue by JensAc** [IENT/RDPlot#35]
The tests on Travis CI fail for a while now. However, on my local machine they pass. I think it is related to 

https://stackoverflow.com/questions/56281631/qapplication-instance-qtbot-fixture-causes-travis-ci-to-abort-and-core-dump

Yet, I am missing the debug capability on the remote VM. I requested debug access from Travis CI. Maybe there will be some progress in the next days.

**Comment by JensAc** [comment]
I am closing this right-away. The Travis-CI was incredibly fast - Many thanks - and I was able to figure out what the problem was. Indeed, adding 
```
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
    - libxcb-randr0-dev
    - libxcb-xtest0-dev
    - libxcb-xinerama0-dev
    - libxcb-shape0-dev
    - libxcb-xkb-dev
    - libxcb-render-util0
    - libxcb-icccm4
    - libxcb-keysyms1
    - libxcb-image0
    ```
    played the trick.
